import {default as Footer} from './Footer'
import {default as Cart} from './Cart'
import {default as FooterBanner} from './FooterBanner'
import {default as HeroBanner} from './HeroBanner'
import {default as Layout} from './Layout'
import {default as Navbar} from './Navbar'
import {default as Product} from './Product'